spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:springhateoas;MODE=MySQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # for test
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true # for test
    show-sql: true # for test
